services:
  app:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/rainwave-library/run.py
    image: ghcr.io/williamjacksn/rainwave-library
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/home/python/rainwave-library
    working_dir: /home/python/rainwave-library

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/rainwave-library
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/home/python/rainwave-library
    working_dir: /home/python/rainwave-library
