services:
  app:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/rainwave-library/run.py
    image: ghcr.io/williamjacksn/rainwave-library
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/home/python/rainwave-library
    working_dir: /home/python/rainwave-library

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/rainwave-library
    working_dir: /home/python/rainwave-library

  ruff:
    image: ghcr.io/astral-sh/ruff
    volumes:
      - ./:/io

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/rainwave-library
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/home/python/rainwave-library
    working_dir: /home/python/rainwave-library
