name: Deploy production app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Configure SSH key
        run: |
          install --mode=600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.ssh_private_key }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H -p 2234 ${{ secrets.ssh_host }} > ~/.ssh/known_hosts

      - name: Pull changes on remote server
        run: ssh ssh://${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:2234 git -C /opt/rainwave-library pull

      - name: Ensure requirements are installed
        run: ssh ssh://${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:2234 /opt/venv/rainwave-library-3.12/bin/pip install --requirement /opt/rainwave-library/requirements.txt

      - name: Restart app
        run: ssh ssh://${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:2234 sudo systemctl restart rainwave-library.service
